#!/bin/bash
#-----------------------------------------------------------------------------#
# Script-name: get_lizenz
#
# 
#
# Author: SCE
#-----------------------------------------------------------------------------#

# load general definitions and functions
if [ ! -f "/etc/config-tools/config_tool_lib" ]; then
  echo "config_tool_lib missing"
  exit 255
fi

. /etc/config-tools/config_tool_lib

if [ "$1" = "MQTT" ]; then
  printf "MQTT74821"
fi 

if [ "$1" = "TEST" ]; then
  printf "TEST74821"
fi 

exit
  